<!DOCTYPE html>
<html lang="fr">
<head>
	<meta charset="UTF-8">
	<title><?php echo $response['page_title']; ?></title>
	<meta name="author" content="<?php echo $response['page_author']; ?>" />
	<meta name="description" content="<?php echo $response['page_description']; ?>" />
	<meta name="viewport" content="width=device-width, initial-scale=1.0">
	
	<style type="text/css">
		<?php readfile('css/reset.css'); ?>
	</style>

</head>
<body>
