</body>

	<!-- CSS -->
	<link rel="stylesheet" type="text/css" href="css/basic.css">
	
	<!-- Script -->
	<script type="text/javascript" src="bower_components/jquery/dist/jquery.min.js"></script>
	<!-- <script type="text/javascript" src="bower_components/angularjs/angular.min.js"></script> -->
	<script type="text/javascript" src="bower_components/scrollReveal.js/scrollReveal.js"></script>
	<script type="text/javascript">
		window.sr = new scrollReveal();
	</script>

</html>